apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  mongodb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  mongodb-password:  {{ .Values.mongodb.password | b64enc | quote }}